/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiChat: typeof import('./src/components/AiChatPanel/AiChat.vue')['default']
    AiChatComposer: typeof import('./src/components/AiChatPanel/components/AiChatComposer.vue')['default']
    AiChatHistorySidebar: typeof import('./src/components/AiChatPanel/components/AiChatHistorySidebar.vue')['default']
    AiChatMessageList: typeof import('./src/components/AiChatPanel/components/AiChatMessageList.vue')['default']
    AiChatPanelHeader: typeof import('./src/components/AiChatPanel/components/AiChatPanelHeader.vue')['default']
    AiChatTrigger: typeof import('./src/components/AiChatPanel/components/AiChatTrigger.vue')['default']
    DeptTreePanel: typeof import('./src/components/DeptTreePanel.vue')['default']
    DocumentCard: typeof import('./src/components/rag/DocumentCard.vue')['default']
    DocumentChunkTree: typeof import('./src/components/rag/DocumentChunkTree.vue')['default']
    DocumentTable: typeof import('./src/components/rag/DocumentTable.vue')['default']
    DocumentUploadDialog: typeof import('./src/components/rag/DocumentUploadDialog.vue')['default']
    DocumentUploader: typeof import('./src/components/rag/DocumentUploader.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    FolderFormDialog: typeof import('./src/components/rag/FolderFormDialog.vue')['default']
    KnowledgeBaseFormDialog: typeof import('./src/components/rag/KnowledgeBaseFormDialog.vue')['default']
    KnowledgeBaseTable: typeof import('./src/components/rag/KnowledgeBaseTable.vue')['default']
    KnowledgeTree: typeof import('./src/components/rag/KnowledgeTree.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
