/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoryCard: typeof import('./src/components/rag/CategoryCard.vue')['default']
    CategoryFormDialog: typeof import('./src/components/rag/CategoryFormDialog.vue')['default']
    DocumentTable: typeof import('./src/components/rag/DocumentTable.vue')['default']
    DocumentUploader: typeof import('./src/components/rag/DocumentUploader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    KnowledgeBaseFormDialog: typeof import('./src/components/rag/KnowledgeBaseFormDialog.vue')['default']
    KnowledgeBaseTable: typeof import('./src/components/rag/KnowledgeBaseTable.vue')['default']
    Pagination: typeof import('./src/components/rag/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/rag/SearchInput.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
